version: '3'

services:
  server:
    container_name: nodejs
    build: './api'
    volumes:
      - ./api/:/node-app
      - ./api/node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '3000:3000'

  db:
    image: 'mongo:4.4.10'
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
